///////////////////////////////////////////////////////////
//  ChargeInformation.cs
//  Implementation of the Class ChargeInformation
//  Generated by Enterprise Architect
//  Created on:      24-6月-2013 23:03:16
//  Original author: Winger
///////////////////////////////////////////////////////////


namespace HospitalSystem.Business
{
    public class ChargeInformation {
      //  public double CardPay { get; set; }已经分开来了，不需要

        public long PatientId { get; set; }

        public string PatientName { get; set; }

      //  public double RegisterPay { get; set; }已经分开来了，不需要

        public double SumPay { get; set; }

        public ChargeInformation()
        {
        }

        public ChargeInformation(long patientId)
        {
            //从数据库中检索到姓名

        }

        public void CountSumPay()
        {
            //从数据库中检索到 所有药价+所有检验价  +CardPay+RegisterPay，写入SumPay 不要cardpay和registerpay了

        }
    }
}//end ChargeInformation