///////////////////////////////////////////////////////////
//  MedicineRecord.cs
//  Implementation of the Class MedicineRecord
//  Generated by Enterprise Architect
//  Created on:      25-6ÔÂ-2013 14:19:18
//  Original author: Winger
///////////////////////////////////////////////////////////


namespace HospitalSystem.Business
{
    public class MedicineRecord 
    {
        public long MedicineId { get; set; }
        public int Number { get; set; }
        public double Price { get; set; }
    }
}//end MedicineRecord