///////////////////////////////////////////////////////////
//  Patient.cs
//  Implementation of the Class Patient
//  Generated by Enterprise Architect
//  Created on:      25-6月-2013 14:19:18
//  Original author: Winger
///////////////////////////////////////////////////////////


using System;
using HospitalSystem.Models;

namespace HospitalSystem.Business
{
    public class Patient
    {
        private teamworkContext db = new teamworkContext();
        private medical_record medical_recordModel;

        public patient patientModel { get; set; }
        public string Department { get; set; }
        public string DiagnosticMessage { get; set; }
        public long PatientId { get; set; }
        public string PatientName { get; set; }
        public int QueueNumber { get; set; }
        public MedicineList MedicineList { get; set; }


        public bool AddPatientMedicalRecord(long doctorId)
        {
            medical_recordModel = new medical_record();
            medical_recordModel.PatientID = PatientId;
            medical_recordModel.DoctorID = doctorId;
            medical_recordModel.DiseaseDescribe = DiagnosticMessage;
            DateTime dateTime = DateTime.Now;
            medical_recordModel.TreatTime = dateTime.ToUniversalTime();
            db.medical_record.Add(medical_recordModel);
            db.SaveChanges();
            //将病历写入数据库
            return true;
        }
    }
}//end Patient