///////////////////////////////////////////////////////////
//  Pharmacy.cs
//  Implementation of the Class Pharmacy
//  Generated by Enterprise Architect
//  Created on:      24-6月-2013 23:03:16
//  Original author: Winger
///////////////////////////////////////////////////////////

namespace HospitalSystem.Business
{
    public class Pharmacy
    {

        private MedicineList medicineList ;

        public Pharmacy(){
            medicineList = new MedicineList();
        }

        /// <summary>
        /// 读取病人Id，更新药品库存数据库
        /// </summary>
        /// <param name="patientId"></param>
        public void dispensing(long patientId){
            //读取Id，检索数据库，填充medicineList

            //根据medicineList中的数据对数据库进行更新
        }

    }
}//end Pharmacy