///////////////////////////////////////////////////////////
//  RegisterQueue.cs
//  Implementation of the Class RegisterQueue
//  Generated by Enterprise Architect
//  Created on:      24-6ÔÂ-2013 23:03:16
//  Original author: Winger
///////////////////////////////////////////////////////////

namespace HospitalSystem.Business
{
    public class RegisterQueue
    {
        public RegisterQueue(long departmentId,string department)
        {
            DepartmentId = departmentId;
            Department = department;
            TotalNumber = 0;
            CurrentNumber = 0;
        }
        public long DepartmentId { get; set; }

        public int CurrentNumber { get; set; }

        public string Department { get; set; }

        public int TotalNumber { get; set; }
    }
}//end RegisterQueue