///////////////////////////////////////////////////////////
//  ExamineRecord.cs
//  Implementation of the Class ExamineRecord
//  Generated by Enterprise Architect
//  Created on:      25-6ÔÂ-2013 14:19:18
//  Original author: Winger
///////////////////////////////////////////////////////////

namespace HospitalSystem.Models
{
    public class ExamineRecord 
    {
        public long examineDetailId { get; set; }
        public double Price { get; set; }
        public string Result { get; set; }
        public long ProductId { get; set; }
        public string productName { get; set; }
        public string productDescript { get; set; }
    }
}//end ExamineRecord