///////////////////////////////////////////////////////////
//  RegisterInformation.cs
//  Implementation of the Class RegisterInformation
//  Generated by Enterprise Architect
//  Created on:      24-6‘¬-2013 23:03:16
//  Original author: Winger
///////////////////////////////////////////////////////////

using System.ComponentModel.DataAnnotations;

namespace HospitalSystem.Models
{
    public class RegisterInformation
    {
        [Required]
        [Display(Name = "≤°»Àid")]
        public long PatientId { get; set; }

        [Required]
        [Display(Name = "π“∫≈ø∆ “")]
        public long DepartmentID { get; set; }

        public string DepartmentName { get; set; }

        public string PatientName { get; set; }

        public long QueueNumber { get; set; }

        public double RegisterMoney { get; set; }
        

    }
}//end RegisterInformation